1045
syssrc/21-ip-assignment pull request #114
Opened 2021-11-16 16:30 UTC by sofyanox12

2021-11-17 01:39 UTC, fitrh requested changes

2021-11-17 01:39 UTC, fitrh commented on src/main/java/ip/syssrc/string/Vocab.java
> +        StringBuffer removed = new StringBuffer(word);
Tidak ada penggunaan `StringBuffer` pada materi ini

2021-11-17 01:46 UTC, sofyanox12 commented on src/main/java/ip/syssrc/string/Vocab.java
> +        StringBuffer removed = new StringBuffer(word);
Kalau StringBuilder bisa kak?

2021-11-17 01:49 UTC, fitrh commented on src/main/java/ip/syssrc/string/Vocab.java
> +        StringBuffer removed = new StringBuffer(word);
Tidak dek, seperti yang saya sampaikan di kelas praktikum,
ada `StringBuffer` dan `StringBuilder` di java untuk string manipulation,
tapi pada praktikum ini, kita bejar string manipulation hanya menggunakan
raw string atau `class String`

2021-11-17 01:58 UTC, sofyanox12 commented on src/main/java/ip/syssrc/string/Vocab.java
> +        StringBuffer removed = new StringBuffer(word);
ohh baik kak.

2021-11-18 10:38 UTC, fitrh requested changes

2021-11-18 10:38 UTC, fitrh commented on src/main/java/ip/syssrc/string/URLParser.java
> +        if (!rawURL.contains("%")) {
Kondisi ini tidak diperlukan, karena membuat `%` -> `%25` tidak ter*encode*

2021-11-18 10:38 UTC, fitrh commented on src/main/java/ip/syssrc/string/URLParser.java
> +        if (!encodedURL.contains("\\") || !encodedURL.contains("/")) {
Sama seperti method `encode`, kondisi ini tidak diperlukan

2021-11-18 10:38 UTC, fitrh commented on src/main/java/ip/syssrc/string/Vocab.java
> +            ++opt;
`foreach` *statement* digunakan jika indeks tidak dibutuhkan, variable `opt` disini
bertindak seperti indeks, jika membutuhkan kondisi yang bergantung pada indeks,
sebaiknya gunakan `for` *statement*

2021-11-18 10:38 UTC, fitrh commented on src/main/java/ip/syssrc/string/Vocab.java
> +        }
Manfaatkan *String method* `replace()`, konversi string ke *chara array*
kemudian me*replace* elemen terakhir sampai elemen ke-4 dari akhir dengan
*null character* merupakan cara yang tidak efisien

2021-11-29 03:03 UTC, merged