Assignment 4 - 1076
syssrc/21-ip-assignment pull request #125
Opened 2021-11-18 07:23 UTC by HasanAzyumardi

2021-11-18 09:58 UTC, fitrh requested changes
Hapus file yang tidak diperlukan, atau kalau dirasa perlu secara pribadi, jangan ikut dicommit ke repo

2021-11-18 09:59 UTC, fitrh commented
Ini assignment 4 atau 5 ?

2021-11-25 11:29 UTC, HasanAzyumardi commented
> 

assignment 4 kak

2021-11-25 13:01 UTC, fitrh commented
Hapus dulu file yang tidak diperlukan

2021-11-25 16:42 UTC, HasanAzyumardi commented
> Hapus dulu file yang tidak diperlukan

sdh kak sy hapus yg App.java

2021-11-26 05:08 UTC, fitrh commented
Pastikan terhapus di repo juga
![20211126_130007_full](https://user-images.githubusercontent.com/55179750/143529885-02b34612-226e-4722-9c8c-209f5c358bca.jpg)

2021-12-15 12:15 UTC, closed without merging