1045 - Tugas Praktikum I & II
syssrc/21-ip-assignment pull request #14
Opened 2021-10-21 03:34 UTC by sofyanox12

2021-10-21 14:29 UTC, fitrh requested changes
Perhatikan [spesifikasi][spec] dan [video referensi][video-ref], dan pastikan program anda berjalan sama atau lebih baik dari apa yang ditampilkan pada [video referensi][video-ref] dan memnuhi semua poin-poin [spesifikasi][spec]

[spec]: https://gist.github.com/fitrh/f6faadd5a967c9d270fa3e73dd42b034#spesifikasi
[video-ref]: https://gist.github.com/fitrh/f6faadd5a967c9d270fa3e73dd42b034#referensi

2021-10-22 17:41 UTC, fitrh requested changes

2021-10-25 14:17 UTC, fitrh requested changes

2021-10-27 14:34 UTC, fitrh requested changes

2021-10-29 16:38 UTC, fitrh approved these changes
Jangan abai persoalan format white space

2021-10-30 01:17 UTC, sofyanox12 commented on src/main/java/ip/syssrc/loop/Eyes.java
> +                if (t==(number-1)){
baik kak

2021-10-30 04:59 UTC, fitrh requested changes

2021-10-30 04:59 UTC, fitrh commented on src/main/java/ip/syssrc/loop/MatricesPad.java
> +                System.out.println(" ");
Baris terakhir merupakan *new line* tanpa *space*

2021-10-30 04:59 UTC, fitrh commented on src/main/java/ip/syssrc/loop/MatricesPad.java
> +            System.out.printf("%0" + d + "d ", i);
Elemen terakhir diakhiri dengan *new line*, bukan *space*

**Contoh Input**

```
0 10 3
```

**Contoh Output**

```
00 01 02
03 04 05
06 07 08
09 10
```

Jika divisualisasikan, baris terakhir seperti berikut

```txt
09<space>10<newline>
```

Sedangkan kode ini akan menghasilkan output berikut

```txt
09<space>10<space>
```

2021-10-30 11:44 UTC, fitrh commented
2 commit terakhir belum memperbaiki review yang saya berikan

2021-10-30 16:13 UTC, fitrh approved these changes

2021-10-30 16:13 UTC, fitrh commented on src/main/java/ip/syssrc/loop/MatricesPad.java
> +            System.out.print(" ");
Jangan mengabaikan penggunan indentasi

2021-10-30 16:13 UTC, fitrh commented on src/main/java/ip/syssrc/loop/MatricesPad.java
> +        System.out.println("\n");
Baris ini sudah tidak diperlukan

2021-10-31 06:20 UTC, fitrh approved these changes

2021-10-31 16:14 UTC, fitrh requested changes

2021-10-31 16:14 UTC, fitrh commented on src/main/java/ip/syssrc/loop/MatricesPad.java
> +                System.out.print("\n");
Baris ini akan mengashilkan *exception* untuk input berikut

```
0 0 1
```

```
0 0 0
```

Untuk kedua input diatas, program menghasilkan output 0

2021-11-01 03:13 UTC, sofyanox12 commented on src/main/java/ip/syssrc/loop/MatricesPad.java
> +                System.out.print("\n");
kak, kalau untuk input start dan end nya sama itu outputnya juga 0?

2021-11-01 03:33 UTC, fitrh commented on src/main/java/ip/syssrc/loop/MatricesPad.java
> +                System.out.print("\n");
Tidak, kalau sama, berarti outputnya angka tersebut

```
10 10 0
```

atau

```
10 10 1
```

Outputnya

```
10
```

2021-11-01 03:46 UTC, fitrh requested changes

2021-11-01 03:46 UTC, fitrh commented on src/main/java/ip/syssrc/loop/MatricesPad.java
> +            }
Tidak pernah ada syarat ini, tetap mencetak angka tersebut

2021-11-01 10:09 UTC, sofyanox12 commented on src/main/java/ip/syssrc/loop/MatricesPad.java
> +            }
ohh baik kak.

2021-11-02 01:57 UTC, fitrh approved these changes

2021-11-02 01:58 UTC, merged